import { GlobalVariables } from "src/Global/globalValues";
import { Level } from "./level"

export class Level3 implements Level {
    constructor() {
    }
    start() {
        // FILE WAS GENERATED BY DCL-EDIT
        // DO NOT MODIFY

        GlobalVariables.shipEntity.getComponent(Transform).position.x = 1;
        GlobalVariables.shipEntity.getComponent(Transform).position.z = 8;
        GlobalVariables.shipEntity.getComponent(Transform).position.y = 0;
        GlobalVariables.shipEntity.getComponent(Transform).scale.setAll(0.85);
        const finalboss5 = new Entity("finalboss")
        engine.addEntity(finalboss5)
        const finalboss5transform = new Transform({
            position: new Vector3(12, 0, 8),
            rotation: new Quaternion(0, 0.04797824, 0, -0.9988484),
            scale: new Vector3(0.5, 0.5, 0.5)
        })
        finalboss5.addComponentOrReplace(finalboss5transform)
        const finalboss5GLTFShape = new GLTFShape("models/enemies/finalboss.glb")
        finalboss5GLTFShape.withCollisions = true
        finalboss5GLTFShape.isPointerBlocker = true
        finalboss5GLTFShape.visible = true
        finalboss5.addComponentOrReplace(finalboss5GLTFShape)

        // FILE WAS GENERATED BY DCL-EDIT
        // DO NOT MODIFY

        const doorMap16 = new Entity("door map 1")
        engine.addEntity(doorMap16)
        const doorMap16transform = new Transform({
            position: new Vector3(5.697, 4.342, 5.136),
            rotation: new Quaternion(0, 0, 0, 1),
            scale: new Vector3(1, 1, 1)
        })
        doorMap16.addComponentOrReplace(doorMap16transform)
        const doorMap16GLTFShape = new GLTFShape("models/maps/door_map_1.glb")
        doorMap16GLTFShape.withCollisions = true
        doorMap16GLTFShape.isPointerBlocker = true
        doorMap16GLTFShape.visible = true
        doorMap16.addComponentOrReplace(doorMap16GLTFShape)

        // FILE WAS GENERATED BY DCL-EDIT
        // DO NOT MODIFY

        const doorwall8 = new Entity("doorwall")
        engine.addEntity(doorwall8)
        const doorwall8transform = new Transform({
            position: new Vector3(-2.055, -5.302, 8),
            rotation: new Quaternion(0, 0, 0, 1),
            scale: new Vector3(0.546, 1, 0.5)
        })
        doorwall8.addComponentOrReplace(doorwall8transform)
        const doorwall8GLTFShape = new GLTFShape("models/maps/doorwall.glb")
        doorwall8GLTFShape.withCollisions = true
        doorwall8GLTFShape.isPointerBlocker = true
        doorwall8GLTFShape.visible = true
        doorwall8.addComponentOrReplace(doorwall8GLTFShape)

        // FILE WAS GENERATED BY DCL-EDIT
        // DO NOT MODIFY

        const startpoint9 = new Entity("startpoint")
        engine.addEntity(startpoint9)
        const startpoint9transform = new Transform({
            position: new Vector3(7.9, -0.032, 7.895),
            rotation: new Quaternion(0, 0, 0, 1),
            scale: new Vector3(0.5, 0.5, 0.5)
        })
        startpoint9.addComponentOrReplace(startpoint9transform)
        const startpoint9GLTFShape = new GLTFShape("models/maps/startpoint.glb")
        startpoint9GLTFShape.withCollisions = true
        startpoint9GLTFShape.isPointerBlocker = true
        startpoint9GLTFShape.visible = true
        startpoint9.addComponentOrReplace(startpoint9GLTFShape)

        // FILE WAS GENERATED BY DCL-EDIT
        // DO NOT MODIFY

        const huecoCarcel11 = new Entity("hueco carcel")
        engine.addEntity(huecoCarcel11)
        const huecoCarcel11transform = new Transform({
            position: new Vector3(7.756, 0, 12.5),
            rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
            scale: new Vector3(0.5, 0.5, 0.5)
        })
        huecoCarcel11.addComponentOrReplace(huecoCarcel11transform)
        const huecoCarcel11GLTFShape = new GLTFShape("models/maps/hueco_carcel.glb")
        huecoCarcel11GLTFShape.withCollisions = true
        huecoCarcel11GLTFShape.isPointerBlocker = true
        huecoCarcel11GLTFShape.visible = true
        huecoCarcel11.addComponentOrReplace(huecoCarcel11GLTFShape)

        // FILE WAS GENERATED BY DCL-EDIT
        // DO NOT MODIFY

        const huecoCarcel12 = new Entity("hueco carcel")
        engine.addEntity(huecoCarcel12)
        const huecoCarcel12transform = new Transform({
            position: new Vector3(7.942, 0, 6),
            rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
            scale: new Vector3(0.5, 0.5, 0.5)
        })
        huecoCarcel12.addComponentOrReplace(huecoCarcel12transform)
        huecoCarcel12.addComponentOrReplace(huecoCarcel11GLTFShape)

        // FILE WAS GENERATED BY DCL-EDIT
        // DO NOT MODIFY
    }
    complete() {
        throw new Error("Method not implemented.")
    }
}